pipeline {
	agent any
	environment {
		pass = credentials('PASSWORD')
	}
	stages {
		stage("Building the Student Survey Image") {
			steps {
				script {
					checkout scm
					sh 'rm -rf *.war'
					sh 'jar -cvf StudentSurvey.war -C 645_HW2/src/main/webapp/ .'
					sh 'echo ${BUILD_TIMESTAMP}'
					sh 'echo ${BUILD_ID}'
					sh 'docker login -u onkar97 -p $pass'
					sh 'pwd'
					sh 'cd 645_HW2/src'
					sh 'docker build -t onkar97/dockerhub:1.6 .'
// 					sh 'docker build https://github.com/onkar97plus/SWE645/blob/571e0f47d0a634b3cc72c0f2596692005ed63249/645_HW2/src/Dockerfile'
					
				}
			}
		}
		stage("Pushing Image to DockerHub") {
			steps {
				script {
					sh'docker push onkar97/dockerhub:${BUILD_TIMESTAMP}'
				}
			}
		}
		stage("Deploying to Rancher as single pod") {
			steps {
				sh 'kubectl set image deployment/stusurvey-pipeline stusurvey-pipeline=onkar97/dockerhub:${BUILD_TIMESTAMP} -n jenkins-pipeline'
			}
		}
		stage("Deploying to Rancher as with load balancer") {
			steps {
				sh 'kubectl set image deployment/studentsurvey645-lb studentsurvey645-lb=onkar97/dockerhub:${BUILD_TIMESTAMP} -n jenkins-pipeline'
			}
		}
	}
}		
									
