apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["project/student"]'
    management.cattle.io/ui-managed: "true"
  creationTimestamp: "2022-04-30T23:35:47Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/targetWorkloadIds: {}
          f:management.cattle.io/ui-managed: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"3d725c1c-a6f2-4359-89b7-c2d904160a14"}: {}
      f:spec:
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":8080,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: agent
    operation: Update
    time: "2022-04-30T23:35:47Z"
  name: student
  namespace: project
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: student
    uid: 3d725c1c-a6f2-4359-89b7-c2d904160a14
  resourceVersion: "2104"
  uid: 9162b90d-fe89-4868-92e2-9510d7bf15e4
spec:
  clusterIP: 10.43.233.112
  clusterIPs:
  - 10.43.233.112
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: swe645
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-project-student
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
